"""This is an auto-generated file mapping a country adjective
like 'Canadian' onto a set of IDs of countries denoted
(typically one).
"""

# ===== Adjective Country Table =====
table = \
{'Afghan': set(['/m/0jdd']),
 'Albanian': set(['/m/06857n', '/m/0jdx']),
 'Algerian': set(['/m/0h3y']),
 'American': set(['/m/09c7w0']),
 'Andorran': set(['/m/0hg5']),
 'Angolan': set(['/m/0j4b']),
 'Aragonian': set(['/m/02srrt']),
 'Argentine': set(['/m/0jgd']),
 'Argentinean': set(['/m/0jgd']),
 'Armenian': set(['/m/0jgx']),
 'Aruban': set(['/m/0j11']),
 'Athenian': set(['/m/03nmzqx']),
 'Aussie': set(['/m/0chghy']),
 'Australian': set(['/m/0chghy']),
 'Austrasia': set(['/m/0gytv']),
 'Austrian': set(['/m/01nhhz', '/m/0h7x']),
 'Azerbaijani': set(['/m/0jhd']),
 'Babylonian': set(['/m/0cn3b']),
 'Bahaman': set(['/m/0160w']),
 'Bahraini': set(['/m/0161c']),
 'Bajun': set(['/m/0162v']),
 'Bangladeshi': set(['/m/0162b']),
 'Barbadian': set(['/m/0162v']),
 'Basotho': set(['/m/04hvw']),
 'Batswana': set(['/m/0166v']),
 'Bavarian': set(['/m/02vkbz_']),
 'Belarusian': set(['/m/0163v']),
 'Belgian': set(['/m/0154j']),
 'Belizean': set(['/m/0164b']),
 'Beninese': set(['/m/0164v']),
 'Bermudan': set(['/m/0165b']),
 'Bhutanese': set(['/m/07bxhl']),
 'Bohemian': set(['/m/0410vqb']),
 'Bolivian': set(['/m/0165v']),
 'Bosnian': set(['/m/0166b']),
 'Brazilian': set(['/m/015fr', '/m/01nr2h']),
 'British': set(['/m/014tss', '/m/07ssc']),
 'Bruneian': set(['/m/0167v']),
 'Bulgarian': set(['/m/015qh', '/m/03bxbql']),
 'Burkinab': set(['/m/01699']),
 'Burkinabe': set(['/m/01699']),
 'Burmese': set(['/m/027g22f', '/m/04xn_']),
 'Burundian': set(['/m/0169t']),
 'Byzantine': set(['/m/017cw']),
 'Cambodian': set(['/m/01xbgx']),
 'Cameroonian': set(['/m/01nln']),
 'Canadian': set(['/m/0d060g']),
 'Cape Verdean': set(['/m/01nqj']),
 'Central African': set(['/m/01nyl']),
 'Chadian': set(['/m/01p1b']),
 'Chechen': set(['/m/0dfrl8']),
 'Chilean': set(['/m/01p1v']),
 'Chinese': set(['/m/0d05w3']),
 'Colombian': set(['/m/01ls2']),
 'Comoran': set(['/m/01n6c']),
 'Confederate': set(['/m/020d5']),
 'Congolese': set(['/m/01rxw', '/m/088xp']),
 'Costa Rican': set(['/m/01p8s']),
 'Croat': set(['/m/01pj7']),
 'Croatian': set(['/m/01pj7', '/m/025scyf']),
 'Cuban': set(['/m/0d04z6']),
 'Cypriot': set(['/m/01ppq']),
 'Czech': set(['/m/01mjq']),
 'Czechoslovakian': set(['/m/01mk6', '/m/05yt6l']),
 'Dane': set(['/m/0k6nt']),
 'Danish': set(['/m/0k6nt']),
 'Djibouti': set(['/m/027jk']),
 'Dominican': set(['/m/027nb', '/m/027rn']),
 'Dutch': set(['/m/049nq', '/m/059j2', '/m/0dv0z']),
 'East Timorese': set(['/m/02lx0']),
 'Ecuadorean': set(['/m/02k1b']),
 'Egyptian': set(['/m/02k54']),
 'Emirian': set(['/m/0c75f', '/m/0j1z8']),
 'English': set(['/m/0210n', '/m/024pcx', '/m/02jx1']),
 'Equatoguinean': set(['/m/02kcz']),
 'Equatorial Guinean': set(['/m/02kcz']),
 'Eritrean': set(['/m/02khs']),
 'Estonian': set(['/m/02kmm']),
 'Ethiopian': set(['/m/019pcs']),
 'Fijian': set(['/m/02wt0']),
 'Filipino': set(['/m/05v8c']),
 'Finn': set(['/m/02vzc']),
 'Finnish': set(['/m/02vzc']),
 'French': set(['/m/0152tq',
                '/m/01flgk',
                '/m/01fmy9',
                '/m/0cn_tpv',
                '/m/0f8l9c',
                '/m/0gtzp']),
 'French Polynesian': set(['/m/02wzv']),
 'Gabonese': set(['/m/03548']),
 'Gambian': set(['/m/0hdx8']),
 'Georgian': set(['/m/0d0kn']),
 'German': set(['/m/01qlyt', '/m/0345h', '/m/03b79']),
 'Ghanaian': set(['/m/035dk']),
 'Greek': set(['/m/035qy', '/m/088q1s']),
 'Grenadian': set(['/m/035yg']),
 'Guadeloupean': set(['/m/037nm']),
 'Guamanian': set(['/m/034tl']),
 'Guatemalan': set(['/m/0345_']),
 'Guinea-Bissauan': set(['/m/036b_']),
 'Guinean': set(['/m/03676']),
 'Guyanese': set(['/m/034m8']),
 'Haitian': set(['/m/03gyl']),
 'Hawaiian': set(['/m/019kzh', '/m/01hlvc']),
 'Herzegovinian': set(['/m/0166b']),
 'Hollander': set(['/m/059j2']),
 'Honduran': set(['/m/03h2c']),
 'Hongkongese': set(['/m/03h64']),
 'Hungarian': set(['/m/02rnb5c', '/m/03gj2', '/m/03l5m1']),
 'I-Kiribati': set(['/m/047t_']),
 'Icelander': set(['/m/03rj0']),
 'Indian': set(['/m/03rk0']),
 'Indonesian': set(['/m/03ryn']),
 'Iranian': set(['/m/03shp']),
 'Iraqi': set(['/m/02p717m', '/m/0d05q4']),
 'Irish': set(['/m/016jz3', '/m/03rt9']),
 'Israeli': set(['/m/03spz']),
 'Italian': set(['/m/02psqkz', '/m/03rjj', '/m/05jt5h']),
 'Ivoirian': set(['/m/0fv4v']),
 'Ivorian': set(['/m/0fv4v']),
 'Jamaican': set(['/m/03_r3']),
 'Japanese': set(['/m/0193qj', '/m/03_3d']),
 'Jordanian': set(['/m/03__y']),
 'Kazakhstani': set(['/m/047lj']),
 'Kenyan': set(['/m/019rg5']),
 'Kirghiz': set(['/m/0jt3tjf']),
 'Kittian': set(['/m/06ryl']),
 'Kiwi': set(['/m/0ctw_b']),
 'Kuwaiti': set(['/m/047yc']),
 'Kyrgyz': set(['/m/0jt3tjf']),
 'Lao': set(['/m/04hhv']),
 'Laotian': set(['/m/04hhv']),
 'Latvian': set(['/m/04g5k']),
 'Lebanese': set(['/m/04hqz']),
 'Liberian': set(['/m/04hzj']),
 'Libyan': set(['/m/04gqr']),
 'Liechtensteiner': set(['/m/04j53']),
 'Lithuanian': set(['/m/04gzd']),
 'Luxembourger': set(['/m/04g61']),
 'Macedonian': set(['/m/0bjv6', '/m/0bk25']),
 'Malagasy': set(['/m/04sj3']),
 'Malawian': set(['/m/04tr1']),
 'Malaysian': set(['/m/09pmkv']),
 'Maldivan': set(['/m/04ty8']),
 'Malian': set(['/m/04v09']),
 'Maltese': set(['/m/04v3q']),
 'Marshallese': set(['/m/04v6v']),
 'Mauritanian': set(['/m/04vjh']),
 'Mauritian': set(['/m/04vs9']),
 'Mexican': set(['/m/0b90_r']),
 'Moldovan': set(['/m/04w4s']),
 'Monacan': set(['/m/04w58']),
 'Monegasque': set(['/m/04w58']),
 'Mongolian': set(['/m/01jv68', '/m/04w8f']),
 'Montenegrin': set(['/m/056vv']),
 'Moroccan': set(['/m/04wgh']),
 'Mosotho': set(['/m/04hvw']),
 'Motswana': set(['/m/0166v']),
 'Mozambican': set(['/m/04wlh']),
 'Myanmarese': set(['/m/04xn_']),
 'Namibian': set(['/m/05bmq']),
 'Nauruan': set(['/m/05br2']),
 'Nepalese': set(['/m/016zwt']),
 'Netherlander': set(['/m/059j2']),
 'Nevisian': set(['/m/06ryl']),
 'New Guinean': set(['/m/09wfqp']),
 'New Zealand': set(['/m/0ctw_b']),
 'Ni-Vanuatu': set(['/m/07z5n']),
 'Nicaraguan': set(['/m/05c74']),
 'Nigerian': set(['/m/05cgv']),
 'Nigerien': set(['/m/05cc1']),
 'North Korean': set(['/m/05b7q']),
 'Northern Irish': set(['/m/05bcl']),
 'Norwegian': set(['/m/05b4w']),
 'Omani': set(['/m/05l8y']),
 'Ottoman': set(['/m/05kyr']),
 'Pakistani': set(['/m/05sb1']),
 'Palauan': set(['/m/05tr7']),
 'Palestinian': set(['/m/01k0p4', '/m/0604m', '/m/0h44w', '/m/0nyg5']),
 'Panamanian': set(['/m/05qx1']),
 'Papua New Guinean': set(['/m/05qkp']),
 'Paraguayan': set(['/m/05v10']),
 'Peruvian': set(['/m/016wzw']),
 'Polish': set(['/m/02z1d_', '/m/03pn9', '/m/05qhw']),
 'Portuguese': set(['/m/0285m87', '/m/05r4w']),
 'Prussian': set(['/m/01k6y1', '/m/020g9r']),
 'Puerto Rican': set(['/m/05r7t']),
 'Qatari': set(['/m/0697s']),
 'Rhodesian': set(['/m/01ptlk', '/m/06jnv']),
 'Roman': set(['/m/03gk2', '/m/06cmp', '/m/06frc', '/m/06gb8']),
 'Romanian': set(['/m/01rdm0', '/m/06c1y']),
 'Russian': set(['/m/06bnz', '/m/0cdbq']),
 'Rwandan': set(['/m/06dfg']),
 'Saint Lucian': set(['/m/06s0l']),
 'Salvadoran': set(['/m/02k8k']),
 'Sammarinese': set(['/m/06sff']),
 'Samoan': set(['/m/06s9y']),
 'San Marinese': set(['/m/06sff']),
 'Saudi': set(['/m/01z215']),
 'Saudi Arabian': set(['/m/01z215']),
 'Saxon': set(['/m/01n45v']),
 'Scottish': set(['/m/06q1r']),
 'Senegalese': set(['/m/06srk']),
 'Serbian': set(['/m/025scy1', '/m/06swt', '/m/077qn', '/m/0821k6']),
 'Seychellois': set(['/m/06sw9']),
 'Sicilian': set(['/m/02zqdb', '/m/0bd46l']),
 'Sierra Leonean': set(['/m/06s_2']),
 'Singaporean': set(['/m/06t2t']),
 'Slovak': set(['/m/06npd']),
 'Slovakian': set(['/m/06npd']),
 'Slovene': set(['/m/06t8v']),
 'Slovenian': set(['/m/06t8v']),
 'Solomon Islander': set(['/m/01n8qg']),
 'Somali': set(['/m/06tgw']),
 'South African': set(['/m/0c4b8', '/m/0hzlz']),
 'South Korean': set(['/m/06qd3']),
 'South Sudanese': set(['/m/05rznz']),
 'Soviet': set(['/m/01mzwp', '/m/05vz3zq']),
 'Spaniard': set(['/m/06mkj']),
 'Spanish': set(['/m/01s47p', '/m/06mkj']),
 'Spartan': set(['/m/09472']),
 'Sri Lankan': set(['/m/06m_5']),
 'Sudanese': set(['/m/06tw8']),
 'Surinamer': set(['/m/06nnj']),
 'Swazi': set(['/m/06v36']),
 'Swede': set(['/m/0d0vqn']),
 'Swedish': set(['/m/01fvhp', '/m/0d0vqn']),
 'Swiss': set(['/m/06mzp']),
 'Syrian': set(['/m/06vbd']),
 'Tadzhik': set(['/m/07dvs']),
 'Taiwanese': set(['/m/06f32']),
 'Tajik': set(['/m/07dvs']),
 'Tanzanian': set(['/m/07dzf']),
 'Thai': set(['/m/07f1x']),
 'Tobagonian': set(['/m/09lxtg']),
 'Togolese': set(['/m/07f5x']),
 'Tongan': set(['/m/07fb6']),
 'Trinidadian': set(['/m/09lxtg']),
 'Tunisian': set(['/m/07fj_']),
 'Turk': set(['/m/01znc_']),
 'Turkish': set(['/m/01znc_']),
 'Turkmen(s)': set(['/m/01c4pv']),
 'Tuvaluan': set(['/m/07fsv']),
 'Ugandan': set(['/m/07tp2']),
 'Ukrainian': set(['/m/07t21']),
 'Uruguayan': set(['/m/07twz']),
 'Uzbek': set(['/m/07t_x']),
 'Uzbekistani': set(['/m/07t_x']),
 'Venezuelan': set(['/m/07ylj']),
 'Vietnamese': set(['/m/01crd5']),
 'Welsh': set(['/m/0576g9', '/m/0j5g9']),
 'West German': set(['/m/082fr']),
 'Western Roman': set(['/m/02jbz2']),
 'Yemeni': set(['/m/01z88t']),
 'Yemenite': set(['/m/01z88t']),
 'Yugoslavian': set(['/m/018j0w', '/m/01hs96', '/m/087vz']),
 'Zairian': set(['/m/0k5vl']),
 'Zambian': set(['/m/088vb']),
 'Zimbabwean': set(['/m/088q4']),
 'Zulu': set(['/m/03gwrmk'])}
