# XXX: Add lexical categories.

translate_metaschema = {
    'HasPlaceOfOrigin': [('P', 'from')],
    'PlaceOfOriginOf': [('P', 'origin of')],
    'Portrayed': [('P', 'portraying')],
    'PortrayedBy': [('P', 'portrayed by')],
    'HasCategory': [('P', 'HasCategory')],
    'HasCategoryMember': [('P', 'HasCategoryMember')],
    'Administers': [('P', 'running')],
    'AdministeredBy': [('P', 'run by')],
    'OccursIn': [('P', 'in')],
    'PlaceOfOccurrenceOf': [('P', 'containing')],
    'Produced': [('P', 'producing')],
    'ProducedBy': [('P', 'produced by')],
    'HasLocation': [('P', 'at')],
    'LocationOf': [('P', 'LocationOf')],
    'HasTitle': [('P', 'titled')],
    'TitleHeldBy': [('P', 'TitleHeldBy')],
    'HasPart': [('P', 'containing')],
    'PartOf': [('P', 'in')],
    'ComposedOf': [('P', 'made of')],
    'Composes': [('P', 'Composes')],
    'ParticipatedIn': [('P', 'participating in')],
    'HasParticipant': [('P', 'having participant')],
    'Discovered': [('P', 'discovering')],
    'DiscoveredBy': [('P', 'discovered by')],
    'HasStatus': [('P', 'HasStatus')],
    'StatusOf': [('P', 'StatusOf')],
    'PractitionerOf': [('P', 'PractitionerOf')],
    'HasPractitioner': [('P', 'HasPractitioner')],
    'HasServiceArea': [('P', 'serving')],
    'ServiceAreaOf': [('P', 'served by')],
    'HasSymbol': [('P', 'HasSymbol')],
    'Symbolizes': [('P', 'Symbolizes')],
    'HasChild': [('P', 'HasChild')],
    'HasParent': [('P', 'HasParent')],
    'HasPublication': [('P', 'HasPublication')],
    'PublicationOf': [('P', 'PublicationOf')],
    'MemberOf': [('P', 'member of')],
    'HasMember': [('P', 'with member')],
    'LeaderOf': [('P', 'leader of')],
    'HasLeader': [('P', 'led by')],
    'HasOwner': [('P', 'owned by')],
    'Owns': [('P', 'owning')],
    'PeerOf': [('P', 'peer of')],
    'HasTimePoint': [('P', 'HasTimePoint')],
    'ExhibitedAt': [('P', 'ExhibitedAt')],
    'Exhibited': [('P', 'Exhibited')],
    'Distributes': [('P', 'distributing')],
    'DistributedBy': [('P', 'distributed by')],
    'HasName': [('P', 'named')],
    'NameOf': [('P', 'NameOf')],
    'SuperclassOf': [('P', 'SuperclassOf')],
    'SubclassOf': [('P', 'SubclassOf')],
    'TookPlaceAt': [('P', 'TookPlaceAt')],
    'HadEventTakePlace': [('P', 'HadEventTakePlace')],
    'HasFictionalRelationship': [('P', 'HasFictionalRelationship')],
    'HasGenre': [('P', 'HasGenre')],
    'GenreOf': [('P', 'GenreOf')],
    'SucceededBy': [('P', 'SucceededBy')],
    'Succeeds': [('P', 'Succeeds')],
    'UsePermittedBy': [('P', 'UsePermittedBy')],
    'PermitsUseOf': [('P', 'PermitsUseOf')],
    'ContributedTo': [('P', 'contributing to')],
    'HasContributor': [('P', 'HasContributor')],
    'HasIdentifier': [('P', 'HasIdentifier')],
    'HasCenter': [('P', 'HasCenter')],
    'CenterFor': [('P', 'CenterFor')],
    'HasCharacter': [('P', 'HasCharacter')],
    'AppearsIn': [('P', 'appearing in')],
    'BroaderThan': [('P', 'BroaderThan')],
    'NarrowerThan': [('P', 'NarrowerThan')],
    'ExpressedBy': [('P', 'ExpressedBy')],
    'UsedToExpress': [('P', 'UsedToExpress')],
    'HasCertification': [('P', 'HasCertification')],
    'CertificationOf': [('P', 'CertificationOf')],
    'HasPreceedingWork': [('P', 'HasPreceedingWork')],
    'HasSubsequentWork': [('P', 'HasSubsequentWork')],
    'Created': [('P', 'Created')],
    'CreatedBy': [('P', 'by')],
    'HasAdaptation': [('P', 'HasAdaptation')],
    'AdaptationOf': [('P', 'AdaptationOf')],
    'HasMeasurement': [('P', 'HasMeasurement')],
    'MeasurementOf': [('P', 'MeasurementOf')],
    'HasAbstraction': [('P', 'HasAbstraction')],
    'AbstractionOf': [('P', 'AbstractionOf')],
    'HasMeansOfDemise': [('P', 'HasMeansOfDemise')],
    'MeansOfDemiseOf': [('P', 'MeansOfDemiseOf')],
    'HasSubject': [('P', 'about')],
    'SubjectOf': [('P', 'subject of')],
    'HasURL': [('P', 'HasURL')],
    'HasOrdinal': [('P', 'HasOrdinal')],
    'Music': [('P', 'Music')],
    'Book': [('P', 'Book')],
    'Medicine': [('P', 'Medicine')],
    'Schema': [('P', 'Schema')],
    'Government': [('P', 'Government')],
    'System': [('P', 'System')],
    'Aviation': [('P', 'Aviation')],
    'Skos': [('P', 'Skos')],
    'Dataworld': [('P', 'Dataworld')],
    'Finance': [('P', 'Finance')],
    'Begin Date': [('P', 'Begin Date')],
    'End Date': [('P', 'End Date')],
    'Date': [('P', 'Date')],
    'HasDescription': [('P', 'HasDescription')],
    'Object': [('P', 'Object')],
    'Address': [('P', 'Address')],
    'Automotive': [('P', 'Automotive')]
}
